# Generated by Django 3.1.3 on 2020-12-01 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20201201_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 13, 17, 59, 459879, tzinfo=utc)),
        ),
    ]
